amcl:
  ros__parameters:
    use_sim_time: true

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: "scan"

    min_particles: 500
    max_particles: 2000

    update_min_d: 0.2
    update_min_a: 0.2

    odom_model_type: "diff"
    alpha1: 0.01
    alpha2: 0.01
    alpha3: 0.02
    alpha4: 0.02

    z_hit: 0.7
    z_short: 0.1
    z_max: 0.1
    z_rand: 0.1
    sigma_hit: 0.3

    tf_broadcast: true
    publish_tf: true
    transform_tolerance: 5.0

    max_beams: 360
