amcl:
  ros__parameters:
    use_sim_time: true

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: "scan"

    min_particles: 100
    max_particles: 2000
    pf_err: 0.05
    pf_z: 0.99

    update_min_d: 2.0
    update_min_a: 1.0

    odom_model_type: "diff-corrected"
    alpha1: 0.0005
    alpha2: 0.0005
    alpha3: 0.0005
    alpha4: 0.0005

    z_hit: 0.9
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.05
    sigma_hit: 0.2

    tf_broadcast: true
    transform_tolerance: 3.0

    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
